### ISSUE TITLE
Shift Keys

### ISSUE THREAD

**Issue by whippingdot** [crizmo/Type-3d#1]
Shift keys do not work (i assume you know this but just noting in case you didn't) such as the excavation mark, percentage symbol, etc.

Other than this I love the design and the way the keys press down. I think those weren't made by you and you had added the button inputs - which all work fluently ignoring shift

**Comment by crizmo** [comment]
OH yes i found the design on code pen heres the link to that - [https://codepen.io/schwiiiii/pen/BarVMxq](https://codepen.io/schwiiiii/pen/BarVMxq)

And there was a issue with the shifts 
document.addEventListener('keydown', keyPressed);
keyPressed does not classify left shift and right shift differently 
so rn either left will work or right

Thx tho imma add it for both now
